spring:
  profiles:
    active: ${ZYRO_ENV:?请设置 ZYRO_ENV=dev 或 prod}

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env.local[.properties]

  main:
    allow-circular-references: true
