spring:
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,file:./static/

  application:
    name: Backend

  devtools:
    restart:
      enabled: false

  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST:smtp.163.com}
    username: ${MAIL_USERNAME:jsk476@163.com}
    password: ${MAIL_PASSWORD:}
    port: ${MAIL_PORT:465}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://db.zyroo.cn:3306/ZyroFrp}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${ZYRO_BACKEND_PORT:?请设置 ZYRO_BACKEND_PORT}

logging:
  level:
    root: WARN

security:
  jwt:
    secret: ${JWT_SECRET:change-me}
    expiration-hours: ${JWT_EXPIRATION_HOURS:24}
